version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile

    ports:
      - "8000:8000"

    environment:
      - DB_PATH=/data/colaboramais.db

    volumes:
      - ./data:/data
      - ./infra:/app/infra

    restart: unless-stopped