services:
  backend:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/data/colaboramais.db
    volumes:
      - db_data:/data
      - ./infra:/app/infra
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend

# ESTA PARTE É OBRIGATÓRIA PARA O VOLUME NOMEADO FUNCIONAR
volumes:
  db_data: