# Estágio 1: Build (igual ao anterior)
FROM node:20-slim AS build
WORKDIR /app
COPY apps/frontend/package*.json ./
RUN npm install
COPY apps/frontend/ .
RUN npm run build

# Estágio 2: Serve
FROM nginx:stable-alpine

# COPIAR A CONFIGURAÇÃO CUSTOMIZADA DO NGINX
COPY infra/docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos compilados
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]